config/routes.rb
Account1::Application.routes.draw do
 root "chits#start"
  resources :chits
  resources :bills
  resources :users
  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :chit
  belongs_to :user
end

app/models/chit.rb
class Chit < ActiveRecord::Base
 has_many :bill
<<<<<<< HEAD
 belongs_to :user
=======
<<<<<<< HEAD
 belongs_to :user
=======
 #belongs_to :user
>>>>>>> 488961c8cea0bca477082f42111113a59e3826a3
>>>>>>> 510c9705ac68f0c11233f36dc70459f62ad77396
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password
end

app/controllers/application_controller.rb
#encoding: UTF-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 510c9705ac68f0c11233f36dc70459f62ad77396
  private
  def require_signin!
  	if current_user.nil?
  		flash[:error] = "bạn cần đăng nhập để tiếp tục"
  		redirect_to signin_url
    end
  end
  helper_method :require_signin!

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
<<<<<<< HEAD
=======
=======
 
>>>>>>> 488961c8cea0bca477082f42111113a59e3826a3
>>>>>>> 510c9705ac68f0c11233f36dc70459f62ad77396
end

app/controllers/bills_controller.rb
#encoding UTF-8
class BillsController < ApplicationController
 before_action :require_signin!, except: [:show, :index]
 def index
   @bills=Bill.all
 end
 
  def new
   @bill=Bill.new
   x=params[:sophieu]
   if(x==nil)
   else
   flash[:notice]="thanh toán cho phiếu chi số "+x
   end
  end
  
  def create
   @bill= Bill.new(bill_params)
   @bill.user = current_user
   if @bill.save
    flash[:notice]= "phiếu thu đã tạo"
	redirect_to @bill
	else
	#nothing
	end
  end
  
  def show
   @bill=Bill.find(params[:id])
  end
  
  def edit
   @bill=Bill.find(params[:id])
  end
  
  def update
   @bill= Bill.find(params[:id])
   @bill.update(bill_params)
   flash[:notice]= "phiếu thu đã cập nhật xong"
   redirect_to @bill
  end
  
  def destroy 
   @bill= Bill.find(params[:id])
   @bill.destroy
   flash[:notice]="phiếu thu đã được xóa"
   redirect_to bills_path
  end
  private
  def bill_params
   params.require(:bill).permit(:serial, :name, :address, :reason, :payment, :ability, :dean, :tabolator, :payer, :cashier)
  end
end

app/controllers/chits_controller.rb
class ChitsController < ApplicationController
<<<<<<< HEAD
 before_action :require_signin!, except: [:show, :index]
=======
<<<<<<< HEAD
 before_action :require_signin!, except: [:show, :index]
=======
#before_action :require_signin!, except: [:show, :index]
>>>>>>> 488961c8cea0bca477082f42111113a59e3826a3
>>>>>>> 510c9705ac68f0c11233f36dc70459f62ad77396
 def start
 end
 
 def index
   @chits=Chit.all
 end
 
 def new
  @chit= Chit.new
 end 
 
 def create
  @chit=Chit.new(chit_params)
  @chit.user = current_user
	if @chit.save
	 flash[:notice]="phiếu chi đã tạo"
	 redirect_to @chit
	else
	#nothing,yet
	end
  end

  def show
    @chit=Chit.find(params[:id])
  end
  
   def edit
    @chit = Chit.find(params[:id])
  end
  
  def update
   @chit=Chit.find(params[:id])
   @chit.update(chit_params)
   flash[:notice]="phiếu chi đã cập nhật xong"
   redirect_to @chit
  end
  
  def destroy
    @chit=Chit.find(params[:id])
	@chit.destroy
	flash[:notice]="phiếu chi đã được xóa"
	redirect_to chits_path
  end
  
  private
  def chit_params
    params.require(:chit).permit(:serial, :name, :address, :reason, :payment, :ability, :dean, :tabolator, :payer, :cashier)
  end
  
end

app/controllers/sessions_controller.rb
#encoding UTF-8
class SessionsController < ApplicationController

 def new
   @user=User.new
 end
 
 def create
   user = User.where(:name => params[:signin][:name]).first
   if user && user.authenticate(params[:signin][:password])
     session[:user_id] = user.id
	   flash[:notice]="đăng nhập thành công"
	   redirect_to root_url 
   else
	   flash[:error]="đăng nhập không thành công"
	   render :new
   end
 end
end

app/controllers/users_controller.rb
#encoding UTF-8
class UsersController < ApplicationController
 def index
  @users =User.all
 end
 def new
  @user = User.new
 end
 
 def create
  @user = User.new(user_params)
  if @user.save
   flash[:notice] = "bạn đã đăng ký thành công"
   redirect_to users_path
   else
   render :new
 end
end

 def show
    @user = User.find(params[:id])
 end

 def edit
    @user = User.find(params[:id])
 end
  
  def update
   @user=User.find(params[:id])
   @user.update(user_params)
   flash[:notice]="thông tin đã được cập nhật"
   redirect_to @user
  end
 
def destroy
  @user = User.find(params[:id])
  @user.destroy
  flash[:notice]= "người dùng đã được xóa"
  redirect_to users_path
end 
private
 def user_params
 params.require(:user).permit(:name, :password, :password_confirmation)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
def title(*parts)
  unless parts.empty?
   content_for :title do
   (parts<< "PHẦN MỀM KẾ TOÁN").join("-")
   end
  end
 end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/chits_helper.rb
module ChitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bills/_form.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%=form_for(@bill) do |f| %>
<table>
 <tr>
  <td><%=f.label:serial, "Số phiếu" %></td>
  <td><%=f.number_field:serial %></td>
 </tr>
 <tr>
  <td><%=f.label:name, "Tên người tạo phiếu" %></td>
  <td><%=f.text_field:name %></td>
 </tr>
 <tr>
  <td><%=f.label:address, "Địa chỉ" %></td>
  <td><%=f.text_field:address %></td>
 </tr>
 <tr>
  <td><%=f.label:reason, "Lý do thu" %></td>
  <td><%=f.text_field:reason %></td>
 </tr>
 <tr>
  <td><%=f.label:payment, "Số tiền" %></td>
  <td><%=f.number_field:payment %></td>
 </tr>
 <tr>
  <td><%=f.label:ability, "Nguồn kinh phí" %></td>
  <td><%=f.text_field:ability %></td>
 </tr>
 <tr>
  <td><%=f.label:dean, "Chủ nhiệm khoa" %></td>
  <td><%=f.text_field:dean %></td>
 </tr>
 <tr>
  <td><%=f.label:payer, "Người nộp tiền" %></td>
  <td><%=f.text_field:payer %></td>
 </tr>
 <tr>
  <td><%=f.label:cashier, "Thủ quỹ" %></td>
  <td><%=f.text_field:cashier %></td>
 </tr>
</table>
 <% if @bill.new_record? %>
 <%=f.submit "Tạo phiếu" %>
 <% else %>
  <%=f.submit "Cập nhật phiếu thu" %>
<% end %>
<% end %>

app/views/bills/edit.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ',{:action=>'start', :controller=>'chits'  }%></h2>
<h2>Sửa phiếu thu</h2>
<%= render "form" %>

app/views/bills/index.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ',{:action=>'start', :controller=>'chits'  }%></h2>
<h2>Danh sách phiếu thu</h2>

<html>
<body>

<table width="1000px" border=1>
	<tr>
		<td><strong>SỐ PHIẾU</strong></td>
		<td><strong>NGÀY THU</strong></td>
		<td><strong>NGƯỜI NHẬN TIỀN</strong></td>
		<td><strong>ĐỊA CHỈ</strong></td>
		<td><strong>LÍ DO THU</strong></td>
		<td><strong>SỐ TIỀN</strong></td>
		<td><strong>NGUỒN KINH PHÍ</strong></td>
		<td><strong>GHI CHÚ</strong></td>
	</tr>
	<% @bills.each do |bill| %>
	<tr>
		<td><li><%=link_to bill.serial, bill %></li></td>
		<td></td>
		<td><li><%=link_to bill.name, bill %></li></td>
		<td><%= bill.address %></td>
		<td><%= bill.reason %></td>
		<td><%= bill.payment %></td>
		<td><%= bill.ability %></td>
		<td></td>
	</tr>
    <% end %>
</table>

<%  total = 0
    @bills.each do |bill|
	   if bill.payment != nil
	   payment = bill.payment
	   total += payment
	   else
	   
	   end
	end
%>
	 
<h1> Tổng thu: <%= total %></h1>
<body>
</html>

app/views/bills/new.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ',{:action=>'start', :controller=>'chits'  }%></h2>
<h2>Phiếu thu mới</h2>
<%= render "form" %>

app/views/bills/show.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<table width=600>
  <tr>
    <td><h2><%=link_to 'Quay lại trang chủ', {:action=>'start', :controller=>'chits'}%>    </h2></td> 
	<td><h2><%=link_to "Phiếu thu mới",new_bill_path %>      </h2></td>
	<td><h2><%=link_to 'Danh sách phiếu thu', :action=>'index'%>   </h2></td>    
  </tr>  
</table>

<% title(@bill.serial, "Bills") %>
<table  width=800>
	<tr>
	<td colspan = 10 align=center></td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left><strong>Đơn vị : Khoa Công nghệ thông tin</strong></td>
	<td colspan = 4 align=center><strong>Mẫu số 01 - TT</strong></td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left><strong>Địa chỉ : P.311, E3, 144 Xuân Thủy, Cầu Giấy, Hà Nội</strong></td>
	<td colspan = 4 align=center>(Ban hành theo QĐ số 15/2006/QĐ-BTC</td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left></td>
	<td colspan = 4 align=center>Ngày 20/03/2006 của Bộ trưởng BTC</td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left></td>
	<td colspan = 4 align=center><strong>Số phiếu : <%=@bill.serial %>/2014</strong></td>
	</tr>
	
	<tr><td></td></tr>
	
	<tr>
	<td colspan = 10 align=center><strong>PHIẾU THU</strong></td>
	</tr>
	
	<tr><td></td></tr>
	<tr><td></td></tr>
	
	<tr>
	<td colspan = 10 align=left >Họ và tên người nộp tiền: <%=@bill.payer %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Địa chỉ: <%=@bill.address %> </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Lý do nộp: <%=@bill.reason %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Số tiền: <%=@bill.payment %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Viết bằng chữ: </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left ><strong>Nguồn kinh phí: <%=@bill.ability %></strong></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Ghi chú: </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=right ><em>Ngày...Tháng 12 Năm 2014</em></td>
	</tr>
	
	<tr><td></td></tr>
	
	<tr>
	<td colspan=3 align=center><strong>Chủ nhiệm khoa</strong></td>
	<td colspan=2 align=center><strong>Thủ quỹ</strong></td>
	<td colspan=2 align=center><strong>Người lập phiếu</strong></td>
	<td colspan=3 align=center><strong>Người nộp tiền</strong></td>
	</tr>
	
	<tr>
	<td colspan=3 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=2 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=2 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=3 align=center><em>(Ký, họ tên)</em></td>
	</tr>
	
	<tr><td></td></tr>
	<tr><td></td></tr>
	<tr><td></td></tr>
	<tr><td></td></tr>
	
	<tr>
	<td colspan=3 align=center><%=@bill.dean %></td>
	<td colspan=2 align=center><%=@bill.cashier %></td>
	<td colspan=2 align=center><%=@bill.name %></td>
	<td colspan=3 align=center><%=@bill.payer %></td>
	</tr>
</table>
<table width=400>
  <tr>
	<td><h2><%=link_to "Sửa phiếu thu",edit_bill_path %>      </h2></td>
	<td><h2><%=link_to "Xóa phiếu thu", bill_path(@bill), method: :delete, data: { confirm: "Bạn có chắc muốn xóa phiếu thu này?"}%>   </h2></td>      
  </tr>  
</table>     
 



app/views/chits/_form.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%=form_for(@chit) do |f| %>
<table>
 <tr>
  <td><%=f.label:serial, "Số phiếu" %></td>
  <td><%=f.number_field:serial %></td>
 </tr>
 <tr>
  <td><%=f.label:name, "Tên người tạo phiếu" %></td>
  <td><%=f.text_field:name %></td>
 </tr>
 <tr>
  <td><%=f.label:address, "Địa chỉ" %></td>
  <td><%=f.text_field:address %></td>
 </tr>
 <tr>
  <td><%=f.label:reason, "Lý do chi" %></td>
  <td><%=f.text_field:reason %></td>
 </tr>
 <tr>
  <td><%=f.label:payment, "Số tiền" %></td>
  <td><%=f.number_field:payment %></td>
 </tr>
 <tr>
  <td><%=f.label:ability, "Nguồn kinh phí" %></td>
  <td><%=f.text_field:ability %></td>
 </tr>
 <tr>
  <td><%=f.label:dean, "Chủ nhiệm khoa" %></td>
  <td><%=f.text_field:dean %></td>
 </tr>
 <tr>
  <td><%=f.label:payer, "Người nhận tiền" %></td>
  <td><%=f.text_field:payer %></td>
 </tr>
 <tr>
  <td><%=f.label:cashier, "Thủ quỹ" %></td>
  <td><%=f.text_field:cashier %></td>
 </tr>
</table>
 <% if @chit.new_record? %>
 <%=f.submit "Tạo phiếu" %>
 <% else %>
  <%=f.submit "Cập nhật phiếu chi" %>
<% end %>
<% end %>

app/views/chits/edit.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ',{:action=>'start', :controller=>'chits'  }%></h2>
<h2>Sửa phiếu chi</h2>
<%= render "form" %>

app/views/chits/index.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ', :action=>'start' %></h2>
<h2>Danh sách phiếu chi</h2>

<html>
<body>
<table width="1000px" border=1>
	<tr>
		<td><strong>SỐ PHIẾU</strong></td>
		<td><strong>NGÀY CHI</strong></td>
		<td><strong>NGƯỜI NHẬN TIỀN</strong></td>
		<td><strong>ĐỊA CHỈ</strong></td>
		<td><strong>LÍ DO CHI</strong></td>
		<td><strong>SỐ TIỀN</strong></td>
		<td><strong>NGUỒN KINH PHÍ</strong></td>
		<td><strong>GHI CHÚ</strong></td>
	</tr>
	<% @chits.each do |chit| %>
	<tr>
		<td><li><%=link_to chit.serial, chit %></li></td>
		<td></td>
		<td><li><%=link_to chit.name, chit %></li></td>
		<td><%= chit.address %></td>
		<td><%= chit.reason %></td>
		<td><%= chit.payment %></td>
		<td><%= chit.ability %></td>
		<td></td>
	</tr>
    <% end %>
</table>

<%  total = 0
    @chits.each do |chit|
	   if chit.payment != nil
	   payment = chit.payment
	   total += payment
	   else
	   
	   end
	end
%>
	 
<h1> Tổng chi: <%= total %></h1>
<body>
</html>

app/views/chits/new.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h2><%=link_to 'Quay lại trang chủ ',{:action=>'start', :controller=>'chits'  }%></h2>
<h2>Phiếu chi mới</h2>
<%= render "form" %>

app/views/chits/show.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<table width=600>
  <tr>
    <td><h2><%=link_to 'Quay lại trang chủ', :action=>'start'%>    </h2></td> 
	<td><h2><%=link_to "Phiếu chi mới",new_chit_path(@chit)%>      </h2></td>
	<td><h2><%=link_to 'Danh sách phiếu chi', :action=>'index'%>   </h2></td>    
  </tr>  
</table>
<% title(@chit.serial, "Chits") %>
<table  width=800>
	<tr>
	<td colspan = 10 align=center></td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left><strong>Đơn vị : Khoa Công nghệ thông tin</strong></td>
	<td colspan = 4 align=center><strong>Mẫu số 01 - TT</strong></td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left><strong>Địa chỉ : P.311, E3, 144 Xuân Thủy, Cầu Giấy, Hà Nội</strong></td>
	<td colspan = 4 align=center>(Ban hành theo QĐ số 15/2006/QĐ-BTC</td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left></td>
	<td colspan = 4 align=center>Ngày 20/03/2006 của Bộ trưởng BTC</td>
	</tr>
	
	<tr>
	<td colspan = 6 align=left></td>
	<td colspan = 4 align=center><strong>Số phiếu : <%=@chit.serial %>/2014</strong></td>
	</tr>
	
	<tr><td></td></tr>
	
	<tr>
	<td colspan = 10 align=center><strong>PHIẾU CHI</strong></td>
	</tr>
	
	<tr><td></td></tr>
	<tr><td></td></tr>
	
	<tr>
	<td colspan = 10 align=left >Họ và tên người nhận tiền: <%=@chit.payer %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Địa chỉ: <%=@chit.address %> </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Lý do nộp: <%=@chit.reason %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Số tiền: <%=@chit.payment %></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Viết bằng chữ: </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left ><strong>Nguồn kinh phí: <%=@chit.ability %></strong></td>
	</tr>
	
	<tr>
	<td colspan = 10 align=left >Ghi chú: </td>
	</tr>
	
	<tr>
	<td colspan = 10 align=right ><em>Ngày...Tháng 12 Năm 2014</em></td>
	</tr>
	
	<tr><td></td></tr>
	
	<tr>
	<td colspan=3 align=center><strong>Chủ nhiệm khoa</strong></td>
	<td colspan=2 align=center><strong>Thủ quỹ</strong></td>
	<td colspan=2 align=center><strong>Người lập phiếu</strong></td>
	<td colspan=3 align=center><strong>Người nhận tiền</strong></td>
	</tr>
	
	<tr>
	<td colspan=3 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=2 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=2 align=center><em>(Ký, họ tên)</em></td>
	<td colspan=3 align=center><em>(Ký, họ tên)</em></td>
	</tr>
	
	<tr><td></td></tr>
	<tr><td></td></tr>
	<tr><td></td></tr>
	<tr><td></td></tr>
	
	<tr>
	<td colspan=3 align=center><%=@chit.dean %></td>
	<td colspan=2 align=center><%=@chit.cashier %></td>
	<td colspan=2 align=center><%=@chit.name %></td>
	<td colspan=3 align=center><%=@chit.payer %></td>
	</tr>
</table>
<table width=600>
  <tr>
	<td><h2><%=link_to "Sửa phiếu chi",edit_chit_path(@chit)%>      </h2></td>
	<td><h2><%=link_to "Xóa phiếu chi", chit_path(@chit), method: :delete, data: { confirm: "Bạn có chắc muốn xóa phiếu chi này?"}%>   </h2></td>
	<td><h2><%=link_to "Thanh toán",{:sophieu=>@chit.serial, :controller=>"bills",:action=>"new"}%>    </h2></td>      
  </tr>  
</table>     
 



app/views/chits/start.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<table width=1000>
<tr>
<td><h2> <%=link_to "Phiếu chi mới",new_chit_path %>    </h2></td>
<td><h2> <%=link_to "Danh sách phiếu chi",chits_path %> </h2></td>
<td><h2> <%=link_to "Phiếu thu mới",new_bill_path %>    </h2></td>
<td><h2> <%=link_to "Danh sách phiếu thu",bills_path %> </h2></td>
</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      PHẦN MỀM KẾ TOÁN
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>



<body>

  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>'>
      <%= value %>
    </div>

    <nav>
  <h2> <%=link_to "Đăng ký", new_user_path %>         </h2>
  <h2> <%=link_to "Đăng nhập", signin_path %>         </h2>
</nav>
  <% end %>


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%= form_for (@user) do |f| %>
<p>
<%= f.label :name, "Username" %><br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :email, "email" %><br>
<%= f.text_field :email %>
</p>

<p>
<%= f.label :password, "password" %><br>
<%= f.password_field :password %>
</p>

<p>
<%= f.label :password_confirmation, "password confirmation" %><br>
<%= f.password_field :password_confirmation %>
</p>

<% if @user.new_record? %>
 <%= f.submit "Đăng ký" %>
<% else %>
 <%= f.submit "cập nhật thông tin" %>
 <%end %>
<% end %>

app/views/users/edit.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%= render "form" %>

app/views/users/index.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<% @users.each do |user| %>
		<td><li><%=link_to user.name, user %></li></td>
		
		
    <% end %>

app/views/users/new.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<h1>ĐĂNG KÝ</h1>
<%= render "form" %>

app/views/users/show.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<%=link_to "sửa thông tin", edit_user_path(@user) %>
<%=link_to "xóa người dùng", user_path(@user), method: :delete, data: { confirm: "Bạn có chắc muốn xóa người dùng này không?"}%>